name: Triage World Requests

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
            submodules: true
      - name: Git Config
        run: |
            git config --global user.email "ci@katelyngigante.com"
            git config --global user.name "Github Actions"
      - name: Install Dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip install -r Archipelago/requirements.txt
            pip install -r scripts/requirements.txt
            python3 scripts/common.py
            [ -e Archipelago/host.yaml ] || echo "{}" >> Archipelago/host.yaml
      - name: Configure host.yaml
        uses: mikefarah/yq@v4.53.3
        with:
            cmd: yq -i '.apworld_manager.github_token = "${{ secrets.GITHUB_TOKEN }}"' Archipelago/host.yaml

      - name: Triage World Request
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
            echo "$ISSUE_BODY" > issue_body.txt
            python3 scripts/add_worlds.py --scan-file issue_body.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
            branch: new-worlds
            title: Triage World Request
            add-paths: 'index/*.json'
            reviewers: silasary
            body: |
                Resolves #${{ github.event.issue.number }}.
